import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { MdOutlineMail } from "react-icons/md";
import { Formik, Form } from "formik";
import * as yup from "yup";

import AuthLayout from "@/components/layouts.tsx/AuthLayout";
import FormikInput from "@/components/inputs/FormikInput";
import Title from "@/components/typography/Title";
import P from "@/components/typography/P";
import Button from "@/components/buttons/Button";
import { toast } from "react-toastify";
import { useRouter } from "next/router";

import Axios from "axios";

const inter = Inter({ subsets: ["latin"] });

const validationSchema = yup.object({
  email: yup.string().required(),
});

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>MOVE IT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <div className="flex flex-col items-center pt-14 md:max-w-[388px] mx-auto">
          <div className="w-full mt-5 text-center md:text-right text-[16px] leading-[20px] text-[#080F50] font-normal">
            <Link href="/" className="">
              Already a member? <span className="text-[#098750]">Sign in</span>
            </Link>
          </div>
          <Formik
            initialValues={{ email: "" }}
            validationSchema={validationSchema}
            onSubmit={async (values, submitProps) => {
              try {
                await Axios.post("/api/forgot-password", values, {
                  headers: {
                    Accept: "application/json",
                    "Content-Type": "application/json",
                  },
                });

                toast("Check your email for the link to reset your password", {
                  hideProgressBar: true,
                  autoClose: 2000,
                  type: "success",
                });
              } catch (error) {
                // console.log(error);
                toast(error.response.data.message, {
                  hideProgressBar: true,
                  autoClose: 2000,
                  type: "error",
                });
              } finally {
                submitProps.setSubmitting(false);
                submitProps.resetForm();
              }
            }}
          >
            {(formik) => {
              return (
                <Form>
                  <div className="flex flex-col justify-center items-center gap-y-[22px]">
                    <div className="text-center">
                      <Title>Forgot Password </Title>
                    </div>
                    <div className="max-w-[447px] text-center">
                      <P>
                        Oops, this can happen to anybody, dont worry we will
                        help you sort this out easily.
                      </P>
                    </div>
                  </div>
                  <div className="mt-10 flex flex-col gap-y-[22px]">
                    <div>
                      <FormikInput
                        name="email"
                        direction="left"
                        icon={<MdOutlineMail color="#098750" />}
                        placeholder="Enter Registered Email"
                      />
                    </div>
                  </div>
                  <div className="mt-5">
                    <Button
                      type="submit"
                      isLoading={formik.isSubmitting}
                      disabled={!formik.isValid || formik.isSubmitting}
                    >
                      Reset Password
                    </Button>
                  </div>
                </Form>
              );
            }}
          </Formik>
        </div>
      </AuthLayout>
    </>
  );
}
