import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { MdOutlineMail } from "react-icons/md";
import { VscKey } from "react-icons/vsc";
import { Formik, Form } from "formik";
import * as yup from "yup";
import { signIn } from "next-auth/react";
import { toast } from "react-toastify";

import AuthLayout from "@/components/layouts.tsx/AuthLayout";
import FormikInput from "@/components/inputs/FormikInput";
import Title from "@/components/typography/Title";
import P from "@/components/typography/P";
import Button from "@/components/buttons/Button";

import { getSession } from "next-auth/react";

import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const validationSchema = yup.object({
  email: yup.string().required(),
  password: yup.string().required(),
});

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>MOVE IT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <div className="flex flex-col items-center pt-14 md:max-w-[388px] mx-auto">
          <div className="flex flex-col justify-center items-center gap-y-[22px]">
            <Title>Sign in</Title>
            <div className="max-w-[447px] text-center">
              <P>
                Welcome back, we exsist to make your money transfers as
                affordable and seamless as possible.
              </P>
            </div>
          </div>
          <Formik
            initialValues={{ email: "", password: "" }}
            validationSchema={validationSchema}
            onSubmit={async (values, submitProps) => {
              try {
                const res: any = await signIn("credentials", {
                  redirect: false,
                  email: values.email,
                  password: values.password,
                  callbackUrl: `${window.location.origin}`,
                });

                res.error
                  ? toast(res.error, {
                      hideProgressBar: true,
                      // autoClose: 2000,
                      type: "error",
                    })
                  : router.push("/dashboard-request");
              } catch (error) {
                // alert(JSON.stringify(error.response));
                toast(error.response.message, {
                  hideProgressBar: true,
                  autoClose: 2000,
                  type: "error",
                });
              } finally {
                submitProps.setSubmitting(false);
                submitProps.resetForm();
              }
            }}
          >
            {(formik) => {
              return (
                <Form>
                  <div className="mt-10 flex flex-col gap-y-[22px]">
                    <div>
                      <FormikInput
                        name="email"
                        direction="left"
                        icon={<MdOutlineMail />}
                        placeholder="Email"
                      />
                    </div>
                    <div>
                      <FormikInput
                        name="password"
                        direction="left"
                        icon={<VscKey />}
                        placeholder="Password"
                      />
                    </div>
                  </div>
                  <div className="w-full mt-5 text-center md:text-right text-[16px] leading-[20px] text-[#080F50] font-normal	">
                    <Link href="/forgot-password" className="">
                      Forgot password?
                    </Link>
                  </div>
                  <div className="mt-5 flex justify-center">
                    <Button
                      type="submit"
                      isLoading={formik.isSubmitting}
                      disabled={!formik.isValid || formik.isSubmitting}
                    >
                      Sign In
                    </Button>
                  </div>
                </Form>
              );
            }}
          </Formik>
        </div>
      </AuthLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/dashboard-request",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
